config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :schedules, only: [:index]
  resources :products, only: [:index, :show]
  resources :fields, only: [:index, :show]
  resources :maps, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:username])
  end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  def index
    
  end

  def show
    
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def index

  end

  def show
    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/fields/index.html.haml
.mainmenu
  .image-wrapper
    = image_tag "yasai.jpg", class: "main-img"
    .image-title
      %p.image-text 一覧から
      %p.image-text HATAKEを
      .img-text-wrapper
        %p.image-text を選ぶ
        = image_tag "kakashi.png", class: "kakashi"

  .fields
    .fields-menu
      %h2.fields-title 畑一覧
      = link_to "新しいHATAKE", "#", class: "new-field-btn btn btn-warning"
    .fields-contents
      - 3.times do |i|
        .field-content
          = link_to field_path(1), class: "content-wrapper" do
            .field-name
              %h3.hatake-name おらが畑#{i + 1}
            %h4 育てている作物：
            %ul.field-products
              %li.field-ptoduct にんじん,
              %li.field-ptoduct ジャガイモ,
              %li.field-ptoduct ホウレンソウ,
              %li.field-ptoduct 里芋,
              %li.field-ptoduct 大根,
            .field-tasked-date
              %h4 最終作業日：
              %p yyyy/mm/dd
            .field-last-task
              %h4 最近完了した作業：
              %P 追肥（ジャガイモ）
            .field-footer
              .field-footer-content
                = link_to "編集する", "#", class: "field-btn edit-btn"
                = link_to "削除する", "#", class: "field-btn delete-btn"

app/views/fields/show.html.haml
.mainmenu
  .image-wrapper
    = image_tag "yasai.jpg", class: "main-img"
    .image-title
      %p.image-text 現在の畑
      %p.image-text おらが畑1
      .img-text-wrapper
        %p.image-text 情報
        = image_tag "kakashi.png", class: "kakashi"

  .fields
    .fields-menu
      %h2.fields-title 作物一覧
    .fields-contents
      - 3.times do |i|
        .field-content
          = link_to field_path(1), class: "content-wrapper" do
            .field-name
              %h3.hatake-name にんじん
            %h4 作業履歴：
            %ul.field-tasks
              - 5.times do |i|
                = link_to product_path(1) do
                  %li.field-task
                    %p.task 豆まき
                    %p.task yyyy/mm/dd
            .field-footer
              .field-footer-content
                = link_to "編集する", "#", class: "field-btn edit-btn"
                = link_to "削除する", "#", class: "field-btn delete-btn"
  .calendar
    .calendar-menu
      %h2.calendar-menu-text 作業履歴/予定
    .calendar-wrapper
      = month_calendar do |date|
        = date.day
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title VegeNavi
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -if user_signed_in?
      = render 'render/header'
    = yield

app/views/maps/index.html.haml
.mainmenu
  .image-wrapper
    = image_tag "yasai.jpg", class: "main-img"
    .image-title
      %p.image-text オカンの畑
      %p.image-text レイアウト
      %p.image-text 研究所
  .maps
    .maps-menu
      %h2.maps-title 作成したレイアウト一覧
      = link_to "新規レイアウト", "#", class: "new-map-btn btn btn-warning"
    - 5.times do |i|
      .map-name
        %p レイアウト名
      = link_to map_path(1), class: "map-link" do
        .map
          .map-line
            .map-piece
            .map-piece
            .map-piece
          .map-line
            .map-piece
            .map-piece
            .map-piece
          .map-line
            .map-piece
            .map-piece
            .map-piece

    

app/views/maps/show.html.haml
.main-menu
  .maps
    .maps-menu
      %h2.maps-title レイアウト名
      = link_to "削除する", "#", class: "new-map-btn btn btn-danger"
    .map-name
      %p 変更を加えたいマスをクリックorタップしてください
    = link_to map_path(1), class: "map-link" do
      .map
        .map-line
          .map-piece
          .map-piece
          .map-piece
        .map-line
          .map-piece
          .map-piece
          .map-piece
        .map-line
          .map-piece
          .map-piece
          .map-piece

app/views/products/index.html.haml
.mainmenu
  .image-wrapper
    = image_tag "yasai.jpg", class: "main-img"
    .image-title
      %p.image-text オカンの畑
      %p.image-text OFFICIAL
      %p.image-text SITE
  %h2.main-title SITEMENU
  .menu-list
    = link_to fields_path, class: "menu-link" do
      = image_tag "field.png", class: "menu-icon"
      .menu-content
        %h3 畑を選ぶ
        %p FIELD
        .span
          .mini-line.y-mini-line
          .bold-line.y-bold-line
    = link_to schedules_path, class: "menu-link" do
      = image_tag "calendar.png", class: "menu-icon"
      .menu-content
        %h3 カレンダー
        %p CALENDAR
        .span
          .mini-line.b-mini-line
          .bold-line.b-bold-line
    = link_to maps_path, class: "menu-link" do
      = image_tag "layout.png", class: "menu-icon"
      .menu-content
        %h3 畑レイアウト
        %p LAYOUT
        .span
          .mini-line.g-mini-line
          .bold-line.g-bold-line
  .schedule
    %h2.main-title 作業予定
    .schedule-contents
      - 3.times do |i|
        = link_to "#", class: "schedule-content" do
          .task-date.content-wrap
            %p.content-name ・予定日
            %p.task-date-db 2021年10月10日
          .product-name.content-wrap
            %p.content-name ・作物
            %p.product-name-db ジャガイモ
          .task-name.content-wrap
            %p.content-name ・作業内容
            %p.task-name-db 土壌調整(苦石)
  .recent-tasks
    %h2.main-title 最近の作業
    .schedule-contents
      - 3.times do |i|
        = link_to "#", class: "schedule-content" do
          .task-date.content-wrap
            %p.content-name ・予定日
            %p.task-date-db 2021年10月10日
          .product-name.content-wrap
            %p.content-name ・作物
            %p.product-name-db ジャガイモ
          .task-name.content-wrap
            %p.content-name ・作業内容
            %p.task-name-db 土壌調整(苦石)

app/views/products/show.html.haml
.mainmenu
  .image-wrapper
    = image_tag "yasai.jpg", class: "main-img"
    .image-title
      %p.image-text おらが畑
      %p.image-text にんじんの
      .img-text-wrapper
        %p.image-text 記録
        = image_tag "kakashi.png", class: "kakashi"

  .tasks
    .tasks-menu
      %h2.tasks-title 作業履歴
    .tasks-contents
      - 3.times do |i|
        .task-content
          .task-name
            %h4.task-main-name 肥料
            %h4.task-sub-name 堆肥（堆）
          %ul.task-tasks
            %li.task-date
              %p.task-day 作業日
              %p.task-day yyyy/mm/dd
          %h5.task-topic-title 備考
          %p.task-topic ここに備考を記入します。改行対応予定です。
          .field-footer
            .field-footer-content
              = link_to "編集する", "#", class: "field-btn edit-btn"
              = link_to "削除する", "#", class: "field-btn delete-btn"
  .calendar
    .calendar-menu
      %h2.calendar-menu-text にんじんの作業履歴/予定
    .calendar-wrapper
      = month_calendar do |date|
        = date.day
  

app/views/render/_header.html.haml
.header-wrapper
  .header
    .header-left
      = link_to root_path do
        = image_tag 'logo.png', class: "header-logo"
    .header-center
      %h2 オカンの畑管理サイト
    .header-right

  .menu
    %span.line#line1
    %span.line#line2
    %span.line#line3
    %p.menu-title MENU

app/views/schedules/index.html.haml
.mainmenu
  .image-wrapper
    = image_tag "yasai.jpg", class: "main-img"
    .image-title
      %p.image-text オカンの畑
      %p.image-text 全作物の
      %p.image-text 予定/履歴

  .calendar
    .calendar-menu
      %h2.calendar-menu-text 全作物の作業履歴/予定
    .calendar-wrapper
      = month_calendar do |date|
        = date.day
        = link_to product_path(1), class: "product-links" do
          %p.product-link 堆肥（にんじん）

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<前月'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '翌月>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>